global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using System.Configuration;
global using Microsoft.Extensions.Configuration;
global using MoralesLarios.OOFP.Types;
global using MoralesLarios.OOFP.Helpers;