// Copyright (c) 2023 Juan Francisco Morales Larios
// moraleslarios@gmail.com
// Licensed under the Apache License, Version 2.0

// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace MoralesLarios.OOFP.EFCore.Infrastructure.Tests.Models.Models;

[Table("AdventureWorksDWBuildVersion")]
public partial class AdventureWorksDwbuildVersion
{
    [Column("DBVersion")]
    [StringLength(50)]
    public string? Dbversion { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? VersionDate { get; set; }
}
